### ISSUE TITLE
IoU is not shown correctly after reloading

### ISSUE THREAD

**Issue by fvisin** [fvisin/main_loop_tf#14]
As reported in https://github.com/fvisin/main_loop_tf/pull/13#pullrequestreview-42837022 there seems to be a problem with the IoU graph when the training is restarted. It probably has to do with the way we compute the incremental counter for the x-axis of the graph, should be verified.

> The only thing I noticed it's that when you reload the parameters and continue the training, the plot of the IoU metrics become a mess

**Comment by marcociccone** [comment]
close because of main refactoring. 
Now metrics are implemented by the user.
