### ISSUE TITLE
Passing the crop size as an argument

### ISSUE THREAD

**Issue by islamtashfiq** [fvisin/main_loop_tf#17]
I know this is a basic question but how can I pass the crop size as an argument?

**Comment by islamtashfiq** [comment]
I solved it. It can be done with argv += ['--crop_size', '[713, 713]'].

**Comment by fvisin** [comment]
Glad you solved! 
Keep in mind that you can pass all the arguments directly from the command line as:

```bash
your_program.py --crop_size [713,713]
```
