### ISSUE TITLE
[Feature Request] Refactor input pipeline

### ISSUE THREAD

**Issue by marcociccone** [fvisin/main_loop_tf#7]
We should find a way to use our dataset_loader with tensorflow Queues: 

Here some suggestions on how to do that:
* https://github.com/tensorflow/tensorflow/issues/7951#issuecomment-283325259
* http://stackoverflow.com/questions/43238984/how-to-enqueue-data-from-a-python-function-into-a-tensorflow-queue

**Comment by fvisin** [comment]
I am not 100% sure there would be an improvement by doing so. We are already doing something very similar to TF's queues in the dataset loaders. The only possible improvement I see over what we do in the dataset loaders would be if TF is able to load the new batch into the GPU (I mean the CPU-->GPU data transfer)  *while* the previous one is being processed. I am not sure whether this is actually being done by the `QueueRunner`. If so, the `feed_dict` approach we adopted should indeed be less convenient.

IIRC we are logging the data loading time and the execution time, before digging into this can you confirm that the input pipeline is actually a bottleneck at the moment?

**Comment by fvisin** [comment]
From my experiments it doesn't look like loading the data is a bottleneck. I am closing it for now, but we can reopen it in the future if there is new evidence that this is an issue.
